package com.hirehub.hirehub_backend.enums;

public enum EmailType {
    SUPPORT_TICKET_CONFIRMATION,
    SUPPORT_TEAM_NOTIFICATION,
    APPLICATION_SUBMITTED,
    APPLICATION_SHORTLISTED,
    APPLICATION_REJECTED,
    INTERVIEW_SCHEDULED,
    RECRUITER_NEW_APPLICATION
}
